export const toDo = [
    {
        id: 1,
        name: "Vũ Chí Triều",
        age: 19,
        date: "2003-09-12",
        sex: "Nam",
    },
    {
        id: 2,
        name: "Vũ Thị A",
        age: 20,
        date: "2002-12-12",
        sex: "Nữ",
    },
    {
        id: 3,
        name: "Vũ Văn B",
        age: 18,
        date: "2004-08-16",
        sex: "Nam",
    },
    {
        id: 4,
        name: "Vũ Chí h",
        age: 18,
        date: "2005-08-16",
        sex: "Nam",
    },
    {
        id: 5,
        name: "Vũ Nguyễn g",
        age: 18,
        date: "2006-08-16",
        sex: "Nam",
    },
    {
        id: 6,
        name: "Vũ Văn f",
        age: 17,
        date: "2007-08-16",
        sex: "Nam",
    },
    {
        id: 7,
        name: "Vũ Ngọc z",
        age: 17,
        date: "2007-08-16",
        sex: "Nữ",
    },
    {
        id: 8,
        name: "Nguyễn Chí t",
        age: 17,
        date: "2007-08-16",
        sex: "Nam",
    },
    {
        id: 9,
        name: "Hoàng thị m",
        age: 17,
        date: "2007-08-16",
        sex: "Nữ",
    },
    {
        id: 10,
        name: "Nguyễn thị k",
        age: 17,
        date: "2007-08-16",
        sex: "Nữ",
    },
]